// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.2011051901     
// 12/10/2012 10:38 рм    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 /// <summary>
/// Copyright (c) 2012 Metadata Technology Ltd.
/// All rights reserved. This program and the accompanying materials
/// are made available under the terms of the GNU Public License v3.0
/// which accompanies this distribution, and is available at
/// http://www.gnu.org/licenses/gpl.html
/// This file is part of the SDMX Component Library.
/// The SDMX Component Library is free software: you can redistribute it and/or modify
/// it under the terms of the GNU General Public License as published by
/// the Free Software Foundation, either version 3 of the License, or
/// (at your option) any later version.
/// The SDMX Component Library is distributed in the hope that it will be useful,
/// but WITHOUT ANY WARRANTY; without even the implied warranty of
/// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
/// GNU General Public License for more details.
/// You should have received a copy of the GNU General Public License
/// along with The SDMX Component Library If not, see <http://www.gnu.org/licenses/>.
/// Contributors:
/// Metadata Technology - initial API and implementation
/// </summary>
///
namespace Org.Sdmxsource.Sdmx.Structureretrieval.Manager.Mutable {
	
	using System.Collections.Generic;
	using Org.Sdmxsource.Sdmx.Api.Manager.Retrieval;
	using Org.Sdmxsource.Sdmx.Api.Manager.Retrieval.Mutable;
	using Org.Sdmxsource.Sdmx.Api.Model.Objects.Reference;
	using Org.Sdmxsource.Sdmx.Api.Model.Objects.Registry;
	using Org.Sdmxsource.Sdmx.Api.Model.Mutable.Registry;
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	/// <summary>
	/// Decorates an ISdmxRetrievalManager to retrieve the immutable structures and create the mutable instances.
	/// </summary>
	///
	public class SdmxMutableProvisionBeanRetrievalManagerImpl : 
			ISdmxMutableProvisionObjectRetrievalManager {
		private IProvisionRetrievalManager provisionBeanRetrievalManager;
	
		public SdmxMutableProvisionBeanRetrievalManagerImpl(
				IProvisionRetrievalManager provisionBeanRetrievalManager0) {
			this.provisionBeanRetrievalManager = provisionBeanRetrievalManager0;
			if (provisionBeanRetrievalManager0 == null) {
				throw new ArgumentException(
						"IProvisionRetrievalManager can not be null");
			}
		}
	
		public virtual IList<IProvisionAgreementMutableObject> GetProvisions(
				IStructureReference xref) {
			IList<IProvisionAgreementMutableObject> returnedProvisions = new List<IProvisionAgreementMutableObject>();
			ISet<IProvisionAgreementObject> provisions = provisionBeanRetrievalManager
					.GetProvisions(xref);
			if (provisions != null) {
				/* foreach */
				foreach (IProvisionAgreementObject currentProvision  in  provisions) {
					returnedProvisions.Add(currentProvision.MutableInstance);
				}
			}
			return returnedProvisions;
		}
	}
}
