//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estat.Nsi.StructureRetriever {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Estat.Nsi.StructureRetriever.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegistryInterface QueryStructureRequest.Refs is null or empty.
        /// </summary>
        internal static string ErrorNoRefsInRequest {
            get {
                return ResourceManager.GetString("ErrorNoRefsInRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0} structure requests are not supported&quot;.
        /// </summary>
        internal static string ErrorNotSupportedFormat1 {
            get {
                return ResourceManager.GetString("ErrorNotSupportedFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegistryInterface QueryStructureRequest is null.
        /// </summary>
        internal static string ErrorNullQueryStructureRequest {
            get {
                return ResourceManager.GetString("ErrorNullQueryStructureRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to retrieve mapping set for dataflow: {0}+{1}+{2}: 
        /// {3}.
        /// </summary>
        internal static string ErrorRetrievingMappingSetFormat4 {
            get {
                return ResourceManager.GetString("ErrorRetrievingMappingSetFormat4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {4}: {0} with id: &apos;{1}&apos;, version: &apos;{2}&apos;, agencyID: &apos;{3}&apos;.
        /// </summary>
        internal static string WarningFormat5 {
            get {
                return ResourceManager.GetString("WarningFormat5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero codes found. Check for missing transcoding rules at Mapping Set {0}, Component {1} for Dataflow {2}.
        /// </summary>
        internal static string ZeroCodesFoundFormat3 {
            get {
                return ResourceManager.GetString("ZeroCodesFoundFormat3", resourceCulture);
            }
        }
    }
}
