// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.2011051901     
// 5/10/2012 7:21 μμ    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 /// <summary>
/// Copyright (c) 2012 Metadata Technology Ltd.
/// All rights reserved. This program and the accompanying materials
/// are made available under the terms of the GNU Public License v3.0
/// which accompanies this distribution, and is available at
/// http://www.gnu.org/licenses/gpl.html
/// This file is part of the SDMX Component Library.
/// The SDMX Component Library is free software: you can redistribute it and/or modify
/// it under the terms of the GNU General Public License as published by
/// the Free Software Foundation, either version 3 of the License, or
/// (at your option) any later version.
/// The SDMX Component Library is distributed in the hope that it will be useful,
/// but WITHOUT ANY WARRANTY; without even the implied warranty of
/// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
/// GNU General Public License for more details.
/// You should have received a copy of the GNU General Public License
/// along with The SDMX Component Library If not, see <http://www.gnu.org/licenses/>.
/// Contributors:
/// Metadata Technology - initial API and implementation
/// </summary>
///

using Org.Sdmxsource.Sdmx.Api.Model.Objects.Base;

namespace Org.Sdmxsource.Sdmx.SdmxObjects.Model.BaseObjects.Metadata {
	
	using Org.Sdmxsource.Sdmx.Api.Manager.Retrieval;
	using Org.Sdmxsource.Sdmx.Api.Model.Metadata;
	using Org.Sdmxsource.Sdmx.Api.Model.BaseObjects.Metadata;
	using Org.Sdmxsource.Sdmx.SdmxObjects.Model.BaseObjects.Base;
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	/// <summary>
	/// Target contains a set of target reference values which when taken together, 
	/// identify the object or objects to which the reported metadata apply.
	/// </summary>
	///
	[Serializable]
	public class TargetObjectBaseCore : ObjectBaseCore, ITargetBase
    {
		private const long serialVersionUID = 5177335379654046347L;
        private IList<IReferenceValueBase> referenceValues;
		private ITarget builtFrom;
	
		public TargetObjectBaseCore(ITarget builtFrom,
				IIdentifiableRetrievalManager retrievalManager) : base(builtFrom) {
			this.referenceValues = new List<IReferenceValueBase>();
			this.builtFrom = builtFrom;
			/* foreach */
			foreach (IReferenceValue referenceValue  in  builtFrom.ReferenceValues) {
				referenceValues.Add(new ReferenceValueObjectBaseCore(referenceValue, retrievalManager));
			}
		}
	
		
		public virtual String Id {
		  get {
				return builtFrom.Id;
			}
		}
		
	
		
		public virtual IList<IReferenceValueBase> ReferenceValues {
		  get {
				return new List<IReferenceValueBase>(referenceValues);
			}
		}
		
	
		
		public ISdmxObject BuiltFrom {
		  get {
				return builtFrom;
			}
		}
		
	}
}
