// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.2011051901     
// 5/10/2012 7:21 μμ    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 /// <summary>
/// Copyright (c) 2012 Metadata Technology Ltd.
/// All rights reserved. This program and the accompanying materials
/// are made available under the terms of the GNU Public License v3.0
/// which accompanies this distribution, and is available at
/// http://www.gnu.org/licenses/gpl.html
/// This file is part of the SDMX Component Library.
/// The SDMX Component Library is free software: you can redistribute it and/or modify
/// it under the terms of the GNU General Public License as published by
/// the Free Software Foundation, either version 3 of the License, or
/// (at your option) any later version.
/// The SDMX Component Library is distributed in the hope that it will be useful,
/// but WITHOUT ANY WARRANTY; without even the implied warranty of
/// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
/// GNU General Public License for more details.
/// You should have received a copy of the GNU General Public License
/// along with The SDMX Component Library If not, see <http://www.gnu.org/licenses/>.
/// Contributors:
/// Metadata Technology - initial API and implementation
/// </summary>
///
namespace Org.Sdmxsource.Sdmx.SdmxObjects.Model.Objects.Base {
	
	using Org.Apache.Xmlbeans;
	using Org.Sdmx.Resources.SdmxMl.Schemas.V20.Common;
	using Org.Sdmx.Resources.SdmxMl.Schemas.V21.Structure;
	using Org.Sdmxsource.Sdmx.Api.Constants;
	using Org.Sdmxsource.Sdmx.Api.Model.Objects.Base;
	using Org.Sdmxsource.Sdmx.Api.Model.Mutable.Base;
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	[Serializable]
	public abstract class ItemCore : NameableCore {
		private const long serialVersionUID = 1L;
	
		///////////////////////////////////////////////////////////////////////////////////////////////////
		////////////BUILD FROM MUTABLE BEAN				 //////////////////////////////////////////////////
		///////////////////////////////////////////////////////////////////////////////////////////////////
		public ItemCore(IItemMutableObject bean, IIdentifiableObject parent) : base(bean, parent) {
		}
	
		///////////////////////////////////////////////////////////////////////////////////////////////////
		////////////BUILD FROM READER                    //////////////////////////////////////////////////
		///////////////////////////////////////////////////////////////////////////////////////////////////	
		//	public ItemCore(SdmxStructureType structure, SdmxReader reader, IIdentifiableObject parent) {
		//		super(structure, reader, parent);
		//	}
	
		///////////////////////////////////////////////////////////////////////////////////////////////////
		////////////BUILD FROM V2.1 SCHEMA				 //////////////////////////////////////////////////
		///////////////////////////////////////////////////////////////////////////////////////////////////
		public ItemCore(ItemType createdFrom,
				SdmxStructureType structureType, IIdentifiableObject parent) : base(createdFrom, structureType, parent) {
		}
	
		///////////////////////////////////////////////////////////////////////////////////////////////////
		////////////BUILD FROM V2 SCHEMA				 //////////////////////////////////////////////////
		///////////////////////////////////////////////////////////////////////////////////////////////////
		public ItemCore(XmlObject createdFrom,
				SdmxStructureType structureType, String id, String uri,
				IList<TextType> name, IList<TextType> description,
				AnnotationsType annotationsType, IIdentifiableObject parent) : base(createdFrom, structureType, id, uri, name, description, annotationsType, parent) {
		}
	
		///////////////////////////////////////////////////////////////////////////////////////////////////
		////////////BUILD FROM V1 SCHEMA				 //////////////////////////////////////////////////
		///////////////////////////////////////////////////////////////////////////////////////////////////
		public ItemCore(
				XmlObject createdFrom,
				SdmxStructureType structureType,
				String id,
				String uri,
				IList<Org.Sdmx.Resources.SdmxMl.Schemas.V10.Common.TextType> name,
				IList<Org.Sdmx.Resources.SdmxMl.Schemas.V10.Common.TextType> description,
				Org.Sdmx.Resources.SdmxMl.Schemas.V10.Common.AnnotationsType annotationsType,
				IIdentifiableObject parent) {
		}
	}
}
