//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estat.Nsi.AuthModule {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Estat.Nsi.AuthModule.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select &lt;password field&gt;  from &lt;table(s)&gt; where ... &lt;user field&gt;={0}.
        /// </summary>
        internal static string DbAuthenticationInvalidSqlQuery {
            get {
                return ResourceManager.GetString("DbAuthenticationInvalidSqlQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SQL for {0}. Please make sure that the sql query in the form: {1}.
        /// </summary>
        internal static string DbAuthInvalidSqlQuery {
            get {
                return ResourceManager.GetString("DbAuthInvalidSqlQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection String name is not set.
        /// </summary>
        internal static string DbAuthMissingConnectionStringName {
            get {
                return ResourceManager.GetString("DbAuthMissingConnectionStringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select &lt;dataflow id&gt; as {0}, &lt;dataflow version&gt; as {1}, &lt;dataflow agency&gt; as {2} from &lt;table(s)&gt; where ... &lt;user field&gt;={3}.
        /// </summary>
        internal static string DbAuthorizationInvalidSqlQuery {
            get {
                return ResourceManager.GetString("DbAuthorizationInvalidSqlQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL query not set.
        /// </summary>
        internal static string DbAuthValidateMissingSql {
            get {
                return ResourceManager.GetString("DbAuthValidateMissingSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the implementation &apos;{0}&apos; for interface {1}.
        /// </summary>
        internal static string ImplementationCannotLoad {
            get {
                return ResourceManager.GetString("ImplementationCannotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation for {0} not set.
        /// </summary>
        internal static string ImplementationMissing {
            get {
                return ResourceManager.GetString("ImplementationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation not set.
        /// </summary>
        internal static string ImplementationMissingAttr {
            get {
                return ResourceManager.GetString("ImplementationMissingAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing authorization implementation.
        /// </summary>
        internal static string MissingAuthorizationImplementation {
            get {
                return ResourceManager.GetString("MissingAuthorizationImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing configuration for module {0}.
        /// </summary>
        internal static string MissingConfiguration {
            get {
                return ResourceManager.GetString("MissingConfiguration", resourceCulture);
            }
        }
    }
}
