//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2009 by the European Commission, represented by Eurostat..
        /// </summary>
        internal static string app_copyright {
            get {
                return ResourceManager.GetString("app_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSI Web Service provider.
        /// </summary>
        internal static string app_description {
            get {
                return ResourceManager.GetString("app_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v{0}.
        /// </summary>
        internal static string app_version {
            get {
                return ResourceManager.GetString("app_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page appears to be have been requested using an external (internet) host name or IP address. External should be able to access the endpoints configured for NSI Web Service using one of the above URLs..
        /// </summary>
        internal static string help_external {
            get {
                return ResourceManager.GetString("help_external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Warning.&lt;/b&gt; This page appears to have been requested using a local or internal host name or IP. The above endpoints are not accessible from external users. Please contact your network administrator to retrieve the external hostname or IP for this web service..
        /// </summary>
        internal static string help_localhost {
            get {
                return ResourceManager.GetString("help_localhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Warning.&lt;/b&gt; This page appears to have been requested using a local or internal host name or IP. The above endpoint URL might not be accessible from external users. Please contact your network administrator to retrieve the external hostname or IP for this web service..
        /// </summary>
        internal static string help_not_external {
            get {
                return ResourceManager.GetString("help_not_external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSI Web Service - Index page.
        /// </summary>
        internal static string index_page_title {
            get {
                return ResourceManager.GetString("index_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoints.
        /// </summary>
        internal static string label_endpoints_info {
            get {
                return ResourceManager.GetString("label_endpoints_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        internal static string label_endpoint_name {
            get {
                return ResourceManager.GetString("label_endpoint_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        internal static string label_endpoint_namespace {
            get {
                return ResourceManager.GetString("label_endpoint_namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint path.
        /// </summary>
        internal static string label_endpoint_path {
            get {
                return ResourceManager.GetString("label_endpoint_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSDL link.
        /// </summary>
        internal static string label_endpoint_wsdl {
            get {
                return ResourceManager.GetString("label_endpoint_wsdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Schema path.
        /// </summary>
        internal static string label_endpoint_xsd {
            get {
                return ResourceManager.GetString("label_endpoint_xsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDMX v2.0 with Eurostat extensions.
        /// </summary>
        internal static string label_estatv20 {
            get {
                return ResourceManager.GetString("label_estatv20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard SDMX v2.0 with Eurostat extensions (No extra element).
        /// </summary>
        internal static string label_estatv20_wcf {
            get {
                return ResourceManager.GetString("label_estatv20_wcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string label_remarks {
            get {
                return ResourceManager.GetString("label_remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Host/IP.
        /// </summary>
        internal static string label_request_host {
            get {
                return ResourceManager.GetString("label_request_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request information.
        /// </summary>
        internal static string label_request_info {
            get {
                return ResourceManager.GetString("label_request_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is usable from external users.
        /// </summary>
        internal static string label_request_is_external {
            get {
                return ResourceManager.GetString("label_request_is_external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string label_request_port {
            get {
                return ResourceManager.GetString("label_request_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string label_request_property {
            get {
                return ResourceManager.GetString("label_request_property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root URL.
        /// </summary>
        internal static string label_request_root_url {
            get {
                return ResourceManager.GetString("label_request_root_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string label_request_value {
            get {
                return ResourceManager.GetString("label_request_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard SDMX v2.0.
        /// </summary>
        internal static string label_stdv20 {
            get {
                return ResourceManager.GetString("label_stdv20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard SDMX v2.0 (No extra element).
        /// </summary>
        internal static string label_stdv20_wcf {
            get {
                return ResourceManager.GetString("label_stdv20_wcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard SDMX v2.1.
        /// </summary>
        internal static string label_stdv21 {
            get {
                return ResourceManager.GetString("label_stdv21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSDL.
        /// </summary>
        internal static string lable_endpoint_link_wsdl {
            get {
                return ResourceManager.GetString("lable_endpoint_link_wsdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDMXMessage.xsd.
        /// </summary>
        internal static string lable_endpoint_link_xsd {
            get {
                return ResourceManager.GetString("lable_endpoint_link_xsd", resourceCulture);
            }
        }
    }
}
