//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.Sdmxsource.Sdmx.EdiParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Org.Sdmxsource.Sdmx.EdiParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension {0} does not have a Cross-Sectional attachment level..
        /// </summary>
        internal static string ErrorDimensionNoCrossSectionalLevelFormat1 {
            get {
                return ResourceManager.GetString("ErrorDimensionNoCrossSectionalLevelFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to level is None.
        /// </summary>
        internal static string ErrorInvalidAttachmentLevel {
            get {
                return ResourceManager.GetString("ErrorInvalidAttachmentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSD {0} {1} does not have a Time Dimension. Only Cross-Sectional data may be requested..
        /// </summary>
        internal static string ErrorNoTimeDimensionFormat2 {
            get {
                return ResourceManager.GetString("ErrorNoTimeDimensionFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call a StartGroup after StartSeries.
        /// </summary>
        internal static string ErrorStartGroupAfterStartSeries {
            get {
                return ResourceManager.GetString("ErrorStartGroupAfterStartSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartGroup not called.
        /// </summary>
        internal static string ErrorStartGroupNotCalled {
            get {
                return ResourceManager.GetString("ErrorStartGroupNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartGroup not called or a StartSeries was called.
        /// </summary>
        internal static string ErrorStartGroupNotCalledOrStartSeriesStarted {
            get {
                return ResourceManager.GetString("ErrorStartGroupNotCalledOrStartSeriesStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartXSObservation not called.
        /// </summary>
        internal static string ErrorStartObsNotCalled {
            get {
                return ResourceManager.GetString("ErrorStartObsNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartSection not called.
        /// </summary>
        internal static string ErrorStartSectionNotCalled {
            get {
                return ResourceManager.GetString("ErrorStartSectionNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartSeries not called.
        /// </summary>
        internal static string ErrorStartSeriesNotCalled {
            get {
                return ResourceManager.GetString("ErrorStartSeriesNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown EDI Prefix for Line : .
        /// </summary>
        internal static string UnknownEDIPrefix {
            get {
                return ResourceManager.GetString("UnknownEDIPrefix", resourceCulture);
            }
        }
    }
}
