// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.2011051901     
// 5/10/2012 7:21 μμ    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 /// <summary>
/// Copyright (c) 2012 Metadata Technology Ltd.
/// All rights reserved. This program and the accompanying materials
/// are made available under the terms of the GNU Public License v3.0
/// which accompanies this distribution, and is available at
/// http://www.gnu.org/licenses/gpl.html
/// This file is part of the SDMX Component Library.
/// The SDMX Component Library is free software: you can redistribute it and/or modify
/// it under the terms of the GNU General Public License as published by
/// the Free Software Foundation, either version 3 of the License, or
/// (at your option) any later version.
/// The SDMX Component Library is distributed in the hope that it will be useful,
/// but WITHOUT ANY WARRANTY; without even the implied warranty of
/// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
/// GNU General Public License for more details.
/// You should have received a copy of the GNU General Public License
/// along with The SDMX Component Library If not, see <http://www.gnu.org/licenses/>.
/// Contributors:
/// Metadata Technology - initial API and implementation
/// </summary>
///

using Org.Sdmxsource.Sdmx.Api.Model.Objects.Datastructure;

namespace Org.Sdmxsource.Sdmx.SdmxObjects.Model.BaseObjects.Categoryscheme {
	
	using Org.Sdmxsource.Sdmx.Api.Constants;
	using Org.Sdmxsource.Sdmx.Api.Exception;
	using Org.Sdmxsource.Sdmx.Api.Manager.Retrieval;
	using Org.Sdmxsource.Sdmx.Api.Model.Objects.Base;
	using Org.Sdmxsource.Sdmx.Api.Model.Objects.Categoryscheme;
	using Org.Sdmxsource.Sdmx.Api.Model.BaseObjects.Categoryscheme;
	using Org.Sdmxsource.Sdmx.SdmxObjects.Model.BaseObjects.Base;
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	[Serializable]
	public class CategorisationObjectBaseCore : MaintainableObjectBaseCore, ICategorisationObjectBase {
		private const long serialVersionUID = 1L;
	
		private ICategorisationObject categorisation;
		private IIdentifiableObject structure;
		private ICategoryObject category;
	
		public CategorisationObjectBaseCore(ICategorisationObject categorisation0,
				ISdmxObjectRetrievalManager retMan) : base(categorisation0) {
			IMaintainableObject maint = retMan.GetMaintainable(categorisation0
					.StructureReference);
			IMaintainableObject cs = retMan.GetMaintainable(categorisation0
					.CategoryReference);
			/* foreach */
			foreach (IIdentifiableObject ident  in  cs.IdentifiableComposites) {
				if (categorisation0.CategoryReference.IsMatch(ident)) {
					category = (ICategoryObject) ident;
					break;
				}
			}
			if (categorisation0.StructureReference.TargetReference.IsMaintainable && categorisation0.StructureReference.IsMatch(maint)) {
				structure = maint;
			} else {
				foreach (IIdentifiableObject ident1  in  maint.IdentifiableComposites) {
					if (categorisation0.StructureReference.IsMatch(ident1)) {
						structure = ident1;
						break;
					}
				}
			}
			if (structure == null) {
				throw new ReferenceException(categorisation0.StructureReference);
			}
			if (category == null) {
				throw new ReferenceException(categorisation0.CategoryReference);
			}
		}
	
		
		public virtual IIdentifiableObject Structure {
		  get {
				return structure;
			}
		}
		
	
		
		public virtual ICategoryObject Category {
		  get {
				return category;
			}
		}
		
	
		
		public ICategorisationObject BuiltFrom {
		  get {
				return categorisation;
			}
		}
		
	}
}
