// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ISdmxMutableProvisionPersistenceManager.cs" company="Eurostat">
//   Date Created : 2013-04-01
//   //   Copyright (c) 2013 by the European   Commission, represented by Eurostat.   All rights reserved.
//   // 
//   //   Licensed under the European Union Public License (EUPL) version 1.1. 
//   //   If you do not accept this license, you are not allowed to make any use of this file.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

namespace Org.Sdmxsource.Sdmx.Api.Manager.Persist.Mutable
{
    #region Using directives

    using Org.Sdmxsource.Sdmx.Api.Model.Mutable.Registry;

    #endregion

    /// <summary>
    ///     Manages the persistence of provisions - this interface deals with mutable Objects, so extra validation is performed to
    ///     ensure the mutable @object conforms to the SDMX rules
    /// </summary>
    public interface ISdmxMutableProvisionPersistenceManager
    {
        #region Public Methods and Operators

        /// <summary>
        /// Deletes the provision agreement
        /// </summary>
        /// <param name="provisionAgreement">The Provision Agreement Mutable Object
        /// </param>
        void DeleteProvision(IProvisionAgreementMutableObject provisionAgreement);

        /// <summary>
        /// Saves the provision agreement
        /// </summary>
        /// <param name="provisionAgreement">The Provision Agreement Mutable Object
        /// </param>
        /// <returns>
        /// ProvisionAgreementMutableObject as a representation of what was saved - with values such as URN generated by the system
        /// </returns>
        IProvisionAgreementMutableObject SaveProvision(IProvisionAgreementMutableObject provisionAgreement);

        #endregion
    }
}