// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.2011051901     
// 5/10/2012 7:21 μμ    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 /// <summary>
/// Copyright (c) 2012 Metadata Technology Ltd.
/// All rights reserved. This program and the accompanying materials
/// are made available under the terms of the GNU Public License v3.0
/// which accompanies this distribution, and is available at
/// http://www.gnu.org/licenses/gpl.html
/// This file is part of the SDMX Component Library.
/// The SDMX Component Library is free software: you can redistribute it and/or modify
/// it under the terms of the GNU General Public License as published by
/// the Free Software Foundation, either version 3 of the License, or
/// (at your option) any later version.
/// The SDMX Component Library is distributed in the hope that it will be useful,
/// but WITHOUT ANY WARRANTY; without even the implied warranty of
/// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
/// GNU General Public License for more details.
/// You should have received a copy of the GNU General Public License
/// along with The SDMX Component Library If not, see <http://www.gnu.org/licenses/>.
/// Contributors:
/// Metadata Technology - initial API and implementation
/// </summary>
///

namespace Org.Sdmxsource.Sdmx.SdmxObjects.Model.BaseObjects.Base {

    using SdmxAPI = Org.Sdmxsource.Sdmx.Api;
    using Org.Sdmxsource.Sdmx.Api.Model.Objects.Base;
	using Org.Sdmxsource.Sdmx.Api.Model.BaseObjects.Base;
	using Org.Sdmxsource.Sdmx.Api.Model.BaseObjects.Codelist;
	using Org.Sdmxsource.Sdmx.Api.Model.BaseObjects.Conceptscheme;
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	[Serializable]
	public abstract class ComponentObjectBaseCore : IdentifiableObjectBaseCore, IComponentObjectBase 
    {
		private const long serialVersionUID = 1L;
		private ICodelistObjectBase Icodelist;
		private IConceptObjectBase IconceptSuper;
        private SdmxAPI.Model.Objects.Base.IComponent Icomponent;
	
		public ComponentObjectBaseCore(Org.Sdmxsource.Sdmx.Api.Model.Objects.Base.IComponent componentBean,
				ICodelistObjectBase codeListBean1, IConceptObjectBase conceptSuperBean2) : base(componentBean) {
			this.Icomponent = componentBean;
			this.Icodelist = codeListBean1;
			if (codeListBean1 == null) {
				this.Icodelist = conceptSuperBean2.CoreRepresentation;
			}
			this.IconceptSuper = conceptSuperBean2;
		}
	
		public virtual ICodelistObjectBase GetCodelist(bool defaultIfRequired) {
			if (Icodelist == null) {
				return IconceptSuper.CoreRepresentation;
			}
			return Icodelist;
		}
	
		
		public virtual IConceptObjectBase Concept {
		  get {
				return IconceptSuper;
			}
		}

	    public virtual ITextFormat TextFormat {
		  get {
				if (Icomponent.Representation != null) {
					return Icomponent.Representation.TextFormat;
				}
				return null;
			}
		}
		
		public IComponent BuiltFrom {
		  get {
				return Icomponent;
			}
		}
		
	}
}
