// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.2011051901     
// 11/10/2012 5:50 μμ    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 /// <summary>
/// Copyright (c) 2012 Metadata Technology Ltd.
/// All rights reserved. This program and the accompanying materials
/// are made available under the terms of the GNU Public License v3.0
/// which accompanies this distribution, and is available at
/// http://www.gnu.org/licenses/gpl.html
/// This file is part of the SDMX Component Library.
/// The SDMX Component Library is free software: you can redistribute it and/or modify
/// it under the terms of the GNU General Public License as published by
/// the Free Software Foundation, either version 3 of the License, or
/// (at your option) any later version.
/// The SDMX Component Library is distributed in the hope that it will be useful,
/// but WITHOUT ANY WARRANTY; without even the implied warranty of
/// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
/// GNU General Public License for more details.
/// You should have received a copy of the GNU General Public License
/// along with The SDMX Component Library If not, see <http://www.gnu.org/licenses/>.
/// Contributors:
/// Metadata Technology - initial API and implementation
/// </summary>
///
namespace Org.Sdmxsource.Sdmx.Structureparser.Builder.BaseObjects.Impl {
	
	using Org.Sdmxsource.Sdmx.Api.Exception;
	using Org.Sdmxsource.Sdmx.Api.Manager.Retrieval;
	using Org.Sdmxsource.Sdmx.Api.Model.Objects.Reference;
	using Org.Sdmxsource.Sdmx.Api.Model.Objects.Registry;
	using Org.Sdmxsource.Sdmx.Api.Model.Superbeans;
	using Org.Sdmxsource.Sdmx.Api.Model.BaseObjects.Registry;
	using Org.Sdmxsource.Sdmx.SdmxObjects.Model.BaseObjects.Registry;
	using Org.Sdmxsource.Sdmx.Structureretrieval.Manager;
	using Org.Sdmxsource.Sdmx.Util.Objects.Container;
	using Org.Springframework.Objects.Factory.Annotation;
	using Org.Springframework.Stereotype;
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	public class RegistrationSuperBeanBuilder : 
			StructureBuilderImpl<IRegistrationObjectBase, IRegistrationObject> {
	
		private ProvisionSuperBeanBuilder provisionSuperBeanBuilder;
	
		public override IRegistrationObjectBase Build(IRegistrationObject buildFrom,
				ISdmxRetrievalManager retrievalManager, SuperBeans existingBeans) {
			if (existingBeans == null) {
				existingBeans = new SuperBeansImpl();
			}
			ISdmxBaseObjectRetrievalManager superBeanRetrievalManager = new InMemoryISdmxBaseObjectRetrievalManager(
					existingBeans);
	
			IMaintainableRefObject provRef = buildFrom.ProvisionAgreementRef
					.MaintainableReference;
			IProvisionAgreementObjectBase provisionSuperBean = null;
	
			provisionSuperBean = superBeanRetrievalManager
					.IGetProvisionAgreementObjectBase(provRef);
	
			if (provisionSuperBean == null) {
				IProvisionAgreementObject provision = retrievalManager
						.GetProvisionAgreementBean(provRef);
				if (provision == null) {
					throw new ValidationException(
							"Error creating Registration ISuper '"
									+ buildFrom.Urn
									+ "'.  Provision reference not found :"
									+ buildFrom.ProvisionAgreementRef
											.TargetUrn);
				}
				provisionSuperBean = provisionSuperBeanBuilder.Build(provision,
						retrievalManager, existingBeans);
				existingBeans.AddProvision(provisionSuperBean);
			}
			return new RegistrationObjectBaseCore(buildFrom, provisionSuperBean);
		}
	}
}
