// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.2011051901     
// 11/10/2012 5:50 μμ    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 /// <summary>
/// Copyright (c) 2012 Metadata Technology Ltd.
/// All rights reserved. This program and the accompanying materials
/// are made available under the terms of the GNU Public License v3.0
/// which accompanies this distribution, and is available at
/// http://www.gnu.org/licenses/gpl.html
/// This file is part of the SDMX Component Library.
/// The SDMX Component Library is free software: you can redistribute it and/or modify
/// it under the terms of the GNU General Public License as published by
/// the Free Software Foundation, either version 3 of the License, or
/// (at your option) any later version.
/// The SDMX Component Library is distributed in the hope that it will be useful,
/// but WITHOUT ANY WARRANTY; without even the implied warranty of
/// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
/// GNU General Public License for more details.
/// You should have received a copy of the GNU General Public License
/// along with The SDMX Component Library If not, see <http://www.gnu.org/licenses/>.
/// Contributors:
/// Metadata Technology - initial API and implementation
/// </summary>
///
namespace Org.Sdmxsource.Sdmx.Structureparser.Builder.BaseObjects.Impl {
	
	using Org.Sdmxsource.Sdmx.Api.Builder;
	using Org.Sdmxsource.Sdmx.Api.Model.Objects.Base;
	using Org.Sdmxsource.Sdmx.Api.Model.BaseObjects.Base;
	using System;
	using System.Collections;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	using org.sdmxsource.sdmx.api.builder;
	
	/// <summary>
	/// This class provides access to the structuralMetadataManager allowing classes extending this class
	/// access to structures that they cross reference
	/// </summary>
	///
	/// <typeparam name="K"></typeparam>
	/// <typeparam name="V"></typeparam>
	public abstract class StructureBuilderImpl<K, V>
		 : BaseObjectBuilder<K, V>  where K : ISuper  where V : ISDMXObject {
	
		/// <summary>
		/// from org.sdmxsource.sdmx.api.builder.BaseObjectBuilder<K,V>
		/// </summary>
		///
		public abstract K Build(
				V buildFrom,
				Org.Sdmxsource.Sdmx.Api.Manager.Retrieval.ISdmxRetrievalManager retrievalManager,
				Org.Sdmxsource.Sdmx.Api.Model.BaseObjects.SuperBeans exitingBeans);
	
	}
}
