// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IQueryProvisionResponseBuilder.cs" company="EUROSTAT">
//   TODO
// </copyright>
// <summary>
//   A class supporting this interface can build error and success QueryProvisioningResponses
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace Org.Sdmxsource.Sdmx.Structureparser.Builder.XmlSerialization.Registry.Response
{
    using System;
    using System.Collections.Generic;

    using Org.Sdmxsource.Sdmx.Api.Constants;
    using Org.Sdmxsource.Sdmx.Api.Model.Objects.Registry;

    using Xml.Schema.Linq;

    /// <summary>
    ///     A class supporting this interface can build error and success QueryProvisioningResponses
    /// </summary>
    public interface IQueryProvisionResponseBuilder
    {
        #region Public Methods and Operators

        /// <summary>
        /// Returns a QueryProvisioningResponse with a failure status along with an
        ///     error message generated from the <paramref name="exception"/>
        /// </summary>
        /// <param name="exception">
        /// The exception generated by the failure
        /// </param>
        /// <param name="schemaVersion">
        /// The schema Version.
        /// </param>
        /// <returns>
        /// The <see cref="XTypedElement"/>.
        /// </returns>
        XTypedElement BuildErrorResponse(Exception exception, SdmxSchemaEnumType schemaVersion);

        /// <summary>
        /// Builds a QueryProvisioningResponse with a success status, along with
        ///     the provisions returned from the query, if there are no provisions returned
        ///     this will be noted in the response message.
        /// </summary>
        /// <param name="provisions">
        /// The source provisions
        /// </param>
        /// <param name="schemaVersion">
        /// The schema Version.
        /// </param>
        /// <returns>
        /// The <see cref="XTypedElement"/>.
        /// </returns>
        XTypedElement BuildSuccessResponse(
            ICollection<IProvisionAgreementObject> provisions, SdmxSchemaEnumType schemaVersion);

        #endregion
    }
}