// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.2011051901     
// 5/10/2012 7:21 μμ    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
 /// <summary>
/// Copyright (c) 2012 Metadata Technology Ltd.
/// All rights reserved. This program and the accompanying materials
/// are made available under the terms of the GNU Public License v3.0
/// which accompanies this distribution, and is available at
/// http://www.gnu.org/licenses/gpl.html
/// This file is part of the SDMX Component Library.
/// The SDMX Component Library is free software: you can redistribute it and/or modify
/// it under the terms of the GNU General Public License as published by
/// the Free Software Foundation, either version 3 of the License, or
/// (at your option) any later version.
/// The SDMX Component Library is distributed in the hope that it will be useful,
/// but WITHOUT ANY WARRANTY; without even the implied warranty of
/// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
/// GNU General Public License for more details.
/// You should have received a copy of the GNU General Public License
/// along with The SDMX Component Library If not, see <http://www.gnu.org/licenses/>.
/// Contributors:
/// Metadata Technology - initial API and implementation
/// </summary>
///

using Org.Sdmxsource.Sdmx.Api.Model.Objects.Datastructure;

namespace Org.Sdmxsource.Sdmx.SdmxObjects.Model.BaseObjects.Registry {
	
	using Org.Sdmxsource.Sdmx.Api.Constants;
	using Org.Sdmxsource.Sdmx.Api.Model.Base;
	using Org.Sdmxsource.Sdmx.Api.Model.Objects.Base;
	using Org.Sdmxsource.Sdmx.Api.Model.Objects.Registry;
	using Org.Sdmxsource.Sdmx.Api.Model.BaseObjects.Registry;
	using Org.Sdmxsource.Sdmx.SdmxObjects.Model.BaseObjects.Base;
	using System;
	using System.Collections;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.IO;
	using System.Runtime.CompilerServices;
	
	[Serializable]
	public class RegistrationObjectBaseCore : MaintainableObjectBaseCore
		, IRegistrationObjectBase {
		private const long serialVersionUID = 3085101294783912114L;
		private readonly IProvisionAgreementObjectBase _prov;
		private readonly IRegistrationObject _builtFrom;
	
		public RegistrationObjectBaseCore(IRegistrationObject reigstrationbean,
				IProvisionAgreementObjectBase provObject) : base(reigstrationbean) {
			this._prov = provObject;
			this._builtFrom = reigstrationbean;
		}
	
		
		public virtual TertiaryBool IndexTimeSeries {
		  get {
				return _builtFrom.IndexTimeSeries;
			}
		}
		
	
		
		public virtual TertiaryBool IndexDataset {
		  get {
				return _builtFrom.IndexDataset;
			}
		}
		
	
		
		public virtual TertiaryBool IndexAttribtues {
		  get {
				return _builtFrom.IndexAttribtues;
			}
		}
		
	
		
		public virtual TertiaryBool IndexReportingPeriod {
		  get {
				return _builtFrom.IndexReportingPeriod;
			}
		}
		
	
		
		public virtual ISdmxDate LastUpdated {
		  get {
				return _builtFrom.LastUpdated;
			}
		}
		
	
		
		public virtual ISdmxDate ValidFrom {
		  get {
				return _builtFrom.ValidFrom;
			}
		}
		
	
		
		public virtual ISdmxDate ValidTo {
		  get {
				return _builtFrom.ValidTo;
			}
		}
		
	
		
		public virtual IDataSource DataSource {
		  get {
				return _builtFrom.DataSource;
			}
		}
		
	
		
		public virtual IProvisionAgreementObjectBase ProvisionAgreement {
		  get {
				return _prov;
			}
		}
		
	
		
		public IRegistrationObject BuiltFrom {
		  get {
				return _builtFrom;
			}
		}
		
	}
}
